spring:
  application:
    name: book-management-api
  datasource:
    url: jdbc:h2:mem:bookdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    initialization-mode: always
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 8080
